### ISSUE TITLE
How are objects linked at submission time?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/hubmap-sample-metadata#3]
How are the disparate object types linked at submission time? [`links`](https://github.com/HumanCellAtlas/metadata-schema/blob/06c1b71988fb38b6ce4ad044c2d5b6641455f6ee/examples/JSON/v5/SmartSeq2/with_links/schema/output-schema.json#L93) are described in the `output-schema.json`... but I don't see a way to indicate relationships during ingest?

**Comment by shirey** [comment]
@mccalluc We need to link objects by their UUID (uuid generated for data at ingest time or at donor/tissue registration in ID System).  The current design for data ingest requires the use to choose a "parent", either tissue or other data.  Am I thinking about the correct "object types"?

**Comment by mccalluc** [comment]
(One note: If it's required, how do the parent of everything (the donor?) get entered into the system?)

Where do we put those UUIDs? To take one example, where would the UUID for the donor go to relate the [clinical metadata](https://github.com/hubmapconsortium/hubmap-sample-metadata/blob/master/workflows/vanderbilt-af/00-clinical-file.json) to the donor? At first, `provenance` looks hopeful, but there's not provision for a pointer in that schema, either.

Alternatively, perhaps rather than recording relationships in these files, there's a manifest that does that? I think you can sort-of do that with HCA `projects`, but that didn't seem right.

**Comment by shirey** [comment]
We should have a discussion with @mruffalo and @cborromeo about this.  Maybe a call?  There are several ways to do this, I was thinking that we would nest children as arrays under their ancestor.  That may not work well, though, to represent a true graph.  Also, that may not work well with a separate schema representing each object type.

**Comment by mccalluc** [comment]
PRs articulating how W3C PROV would be used for this have been approved. Closing.
