### ISSUE TITLE
Specify our own HuBMAP specific restrictions?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/hubmap-sample-metadata#4]
I think we would want supplementary schemas to ensure that the data we receive matches our needs. In particular:
- Pin the version numbers.
- Possibly add more required fields?
- Possibly add more optional fields?
- Possibly add `"additionalProperties": false`?

**Comment by shirey** [comment]
We're definitely going to need to extend what is there.  We'll need to add a lot for image metadata as well as donor.

**Comment by mccalluc** [comment]
It feels like we may be making our own type schemas, but still referencing their core types. I'll file separate issues for gathering specs for image and donor. Keeping this open for the high-level issue: Is making our own schemas the way to go, or should we be asking HCA to extend theirs?
