### ISSUE TITLE
Get more sample workflow diagrams

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/hubmap-sample-metadata#8]
I think we want at least 3 workflows in here before feeling confident that it is a general solution. Vinay at DBMI said he'd get me a description of the work they're doing. Other good resources?

**Comment by shirey** [comment]
Will these work?
https://drive.google.com/drive/folders/1bxHX3UW9skWVSjHMM2LtDhVtJyhXwptz

**Comment by mccalluc** [comment]
Yes. Thanks!
