### ISSUE TITLE
What format will data be delivered to us? (Probably tabular, then template into json.)

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/hubmap-sample-metadata#9]
How will the metadata actually be delivered to us? My guess is that it will be tabular, and then we'll be responsible for templating it into json.
- Is that correct?
- Demonstrate: the fixtures here should eventually be closer to the real user input, and then we'll construct json from that.

**Comment by shirey** [comment]
Yes, tabular- csv, tsv or xlsx is what we're thinking now.  And, yes, we'll convert to json.

**Comment by mccalluc** [comment]
answered
